# Modify and copy to:
#  - ~/.config/broot/conf.toml (Linux)
#  - ~/Library/Preferences/org.dystroy.broot/conf.toml (Mac)

default_flags = ""

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
key = "ctrl-d"
execution = "cd {directory}"
from_shell = true

[[verbs]]
key = "ctrl-e"
execution = "$EDITOR {file}"
from_shell = true

[[verbs]]
key = "ctrl-u"
execution = ":up_tree"

[[verbs]]
invocation = "edit"
key = "enter"
execution = "$EDITOR {file}"
apply_to = "file"

[special-paths]
"/home/user/.Private" = "hide"
"/Users/user/Library" = "hide"

[skin]
input = "ansi(251) none"
